#This is the default config

enable-pvpstats: false

disabled-worlds:
  - world
  - city

Scoreboard:
  Title: '&a&lStats'
  #seconds
  Update-delay: 60
  Items:
    1:
      Title: '&aOnline'
      Type: '%online%'
#    2:
#      Title: '&cMoney'
#      Type: '%eco%'
#    3:
#      Title: '&9Level'
#      Type: '%powlevel%'