#This is the default config

enable-pvpstats: true

disabled-worlds:
  - world_nether
  - city

Scoreboard:
  Title: '&a&lStats'
  #seconds
  # For instant updates you can or 1 and it will update every second
  Update-delay: 1
  Items:
    #Title: Type
    '&9Online': '%online%'
    '&9Money': '%econ%'