#This is the default config

enable-pvpstats: false

disabled-worlds:
  - world_nether
  - city

Scoreboard:
  Title: '&a&lStats'
  #seconds
  Update-delay: 60
  Items:
    #Title: Type
    '&9Online': '%online%'
    '&9Money': '%econ%'